title:  Džoka Mitrov
tagline:    thoughts about Dynamics NAV and F#
author:
  name: 'Džoka'
  twitter:  _dzmi

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'mitrov-github-io'

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/mitrov'}
- {icon: 'twitter', link: 'https://twitter.com/_dzmi'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
